CREATE TYPE gender_enum AS ENUM ('мужской', 'женский');
CREATE TYPE company_type_enum AS ENUM ('реаб.центр');
CREATE TYPE company_role_enum AS ENUM ('клиент', 'поставщик', 'партнер');
CREATE TYPE manager_type_enum AS ENUM ('нет', 'лидоруб', 'хантер', 'фермер');
CREATE TYPE document_type_enum AS ENUM ('диплом', 'сертификат', 'паспорт', 'прописка', 'свидетельство смены фамилии', 'СНИЛС', 'повышение кваливикации', 'договор на обучение');
CREATE TYPE document_status_enum AS ENUM('действителен', 'истёк', 'отозван');
CREATE TYPE product_type_enum AS ENUM('оналайн', 'очно');
--CREATE TYPE type_good_enum AS ENUM();
CREATE TYPE price_type_enum AS ENUM('базовая с рассрочкой', 'внутренняя рассрочка +15%', 'офлайн', 'распродажа без рассрочки для ОМ', 'скидка при полной оплате для ОП', 'спец цена', 'доп доступ');
CREATE TYPE how_found_us_enum AS ENUM ('сарафанное радио', 'в Контакте', 'вебинар', 'поисковик');
CREATE TYPE preferred_channels_enum AS ENUM ('звонок', 'Telegram', 'WhatsApp', 'e-mail');
CREATE TYPE webinar_type_enum AS ENUM ('вебинар', 'автовебинар');
